name: GitHub Workflow

on:
  push:
    branches:
      - 'master'
      - 'stable-*'
  pull_request:
    branches:
      - 'master'
      - 'stable-*'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: debian:11
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
    - uses: actions/checkout@v2
    - name: Gather system information
      run: |
        mkdir -p "${HOME}/info"
        cd "${HOME}/info"
        echo 2 > num_threads
    - name: Install required packages
      run: |
        apt-get update
        apt-get install --no-install-recommends -yyy \
          ca-certificates \
          ccache \
          cmake \
          docbook-xml \
          docbook-xsl \
          fop \
          g++ \
          git \
          libclucene-dev \
          libsword-dev \
          libqt5svg5-dev \
          libqt5xmlpatterns5-dev \
          make \
          pkg-config \
          po4a \
          qtbase5-dev \
          qtdeclarative5-dev \
          qttools5-dev \
          qtwebengine5-dev \
          xsltproc
    - name: Configure the build
      run: |
        mkdir -p "${HOME}/local" build
        cd build
        cmake "-DCMAKE_PREFIX_PATH=${HOME}/local/" "-DCMAKE_INSTALL_PREFIX=${HOME}/local/" ..
    - name: Compile
      run: make "-j$(cat "${HOME}/info/num_threads")"
      working-directory: build
    - name: Install
      run: make "-j$(cat "${HOME}/info/num_threads")" install
      working-directory: build
    - uses: actions/upload-artifact@v4
      if: success()
      with:
        name: handbooks
        path: '~/local/share/doc/bibletime/handbook/'
    - uses: actions/upload-artifact@v4
      if: success()
      with:
        name: howtos
        path: '~/local/share/doc/bibletime/howto/'
